name: Generate controls diagram

on:
  push:

jobs:
  chickencoop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout robot code
        uses: actions/checkout@v2
        with:
          path: 'toothless'
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'site'
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Create output directory
        run: mkdir -p site/diagrams/$GITHUB_REF_NAME
      - name: Generate diagrams
        run: |
          npx chickencoop -i toothless/src/main/java/org/team1540/robot2022/RobotContainer.java -o site/diagrams/$GITHUB_REF_NAME/controls.pdf --error
          npx chickencoop -i toothless/src/main/java/org/team1540/robot2022/utils/FeatherClient.java -o site/diagrams/$GITHUB_REF_NAME/feather_client.pdf --error
      - name: commit and push
        run: |
          cd site
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add diagrams/$GITHUB_REF_NAME/controls.pdf
          git add diagrams/$GITHUB_REF_NAME/feather_client.pdf
          git commit -m "refactor: update diagrams"
          git push
